// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_0Veb60um4lT3Y5uVTUpAU9BgTwYVGNo',
    appId: '1:839395739146:web:122261cdd737b6651001f3',
    messagingSenderId: '839395739146',
    projectId: 'pickabo-2fe7f',
    authDomain: 'pickabo-2fe7f.firebaseapp.com',
    databaseURL: 'https://pickabo-2fe7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickabo-2fe7f.firebasestorage.app',
    measurementId: 'G-Z26TTDJF9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxF3Go22efQYm7LMDKJGWg-vHmWq5rQs',
    appId: '1:839395739146:android:a8c72cc3313f39211001f3',
    messagingSenderId: '839395739146',
    projectId: 'pickabo-2fe7f',
    databaseURL: 'https://pickabo-2fe7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickabo-2fe7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4coFMVYeDA3hqb24a3a900jYz8O9SkTM',
    appId: '1:839395739146:ios:390105fe8cc299031001f3',
    messagingSenderId: '839395739146',
    projectId: 'pickabo-2fe7f',
    databaseURL: 'https://pickabo-2fe7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickabo-2fe7f.firebasestorage.app',
    iosBundleId: 'com.arnob.purplechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4coFMVYeDA3hqb24a3a900jYz8O9SkTM',
    appId: '1:839395739146:ios:390105fe8cc299031001f3',
    messagingSenderId: '839395739146',
    projectId: 'pickabo-2fe7f',
    databaseURL: 'https://pickabo-2fe7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickabo-2fe7f.firebasestorage.app',
    iosBundleId: 'com.arnob.purplechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_0Veb60um4lT3Y5uVTUpAU9BgTwYVGNo',
    appId: '1:839395739146:web:25a3c3706eb06c021001f3',
    messagingSenderId: '839395739146',
    projectId: 'pickabo-2fe7f',
    authDomain: 'pickabo-2fe7f.firebaseapp.com',
    databaseURL: 'https://pickabo-2fe7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickabo-2fe7f.firebasestorage.app',
    measurementId: 'G-BER35BPZF6',
  );
}
